<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <_WebToolingArtifacts Remove="Properties\PublishProfiles\Default.pubxml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.0" />
		<PackageReference Include="XTI_Core.Extensions" Version="1.10.26-dev251122155254802" />
		<PackageReference Include="XTI_Processes" Version="1.10.26-dev251122155254802" />
	</ItemGroup>
</Project>
