// Generated Code
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using XTI_App.Abstractions;
global using XTI_App.Api;
global using XTI_Hub;
global using XTI_HubDB.Entities;
global using XTI_HubWebAppApi;
global using XTI_HubWebAppApi.Installations;
global using XTI_HubWebAppApi.Logs;
global using XTI_HubWebAppApi.ResourceGroupInquiry;
global using XTI_HubWebAppApi.ResourceInquiry;
global using XTI_HubWebAppApi.UserGroups;
global using XTI_WebApp.Abstractions;
global using XTI_WebApp.Api;