global using XTI_Hub.Abstractions;
global using XTI_HubWebAppApi;
global using XTI_HubWebAppApi.Auth;
global using XTI_HubWebAppApi.UserMaintenance;
global using XTI_TempLog.Abstractions;
global using XTI_App.Abstractions;
global using XTI_WebApp.Abstractions;
global using XTI_ODataQuery.Api;
global using XTI_HubDB.Entities;