// Generated Code
namespace XTI_HubAppClient;
public sealed partial class InstallationsGroup : AppClientGroup
{
    public InstallationsGroup(IHttpClientFactory httpClientFactory, XtiTokenAccessor xtiTokenAccessor, AppClientUrl clientUrl, AppClientOptions options) : base(httpClientFactory, xtiTokenAccessor, clientUrl, options, "Installations")
    {
        Actions = new InstallationsGroupActions(BeginDelete: CreatePostAction<InstallationIDRequest, EmptyActionResult>("BeginDelete"), BeginInstallation: CreatePostAction<BeginInstallationRequest, InstallationModel>("BeginInstallation"), BeginRequestedInstallation: CreatePostAction<AppCommandIDRequest, AppCommandModel>("BeginRequestedInstallation"), BeginRequestedInstallationStep: CreatePostAction<BeginAppCommandStepRequest, AppCommandStepModel>("BeginRequestedInstallationStep"), Deleted: CreatePostAction<InstallationIDRequest, EmptyActionResult>("Deleted"), GetInstallationActivities: CreatePostAction<GetInstallationActivitiesRequest, InstallationActivitiesResult>("GetInstallationActivities"), GetInstallationDetail: CreatePostAction<InstallationIDRequest, InstallationDetailModel>("GetInstallationDetail"), GetRequestedInstallationDetail: CreatePostAction<AppCommandIDRequest, AppInstallCommandDetailModel>("GetRequestedInstallationDetail"), Index: CreateGetAction<InstallationQueryRequest>("Index"), Installation: CreateGetAction<InstallationViewRequest>("Installation"), Installed: CreatePostAction<InstallationIDRequest, EmptyActionResult>("Installed"), RequestDelete: CreatePostAction<InstallationIDRequest, EmptyActionResult>("RequestDelete"), RequestedInstallationEnded: CreatePostAction<AppCommandIDRequest, EmptyActionResult>("RequestedInstallationEnded"), RequestedInstallationStepEnded: CreatePostAction<AppCommandStepEndedRequest, EmptyRequest>("RequestedInstallationStepEnded"), RequestInstallation: CreatePostAction<AddAppInstallCommandRequest, AppInstallCommandDetailModel>("RequestInstallation"));
        Configure();
    }

    partial void Configure();
    public InstallationsGroupActions Actions { get; }

    public Task<EmptyActionResult> BeginDelete(InstallationIDRequest requestData, CancellationToken ct = default) => Actions.BeginDelete.Post("", requestData, ct);
    public Task<InstallationModel> BeginInstallation(BeginInstallationRequest requestData, CancellationToken ct = default) => Actions.BeginInstallation.Post("", requestData, ct);
    public Task<AppCommandModel> BeginRequestedInstallation(AppCommandIDRequest requestData, CancellationToken ct = default) => Actions.BeginRequestedInstallation.Post("", requestData, ct);
    public Task<AppCommandStepModel> BeginRequestedInstallationStep(BeginAppCommandStepRequest requestData, CancellationToken ct = default) => Actions.BeginRequestedInstallationStep.Post("", requestData, ct);
    public Task<EmptyActionResult> Deleted(InstallationIDRequest requestData, CancellationToken ct = default) => Actions.Deleted.Post("", requestData, ct);
    public Task<InstallationActivitiesResult> GetInstallationActivities(GetInstallationActivitiesRequest requestData, CancellationToken ct = default) => Actions.GetInstallationActivities.Post("", requestData, ct);
    public Task<InstallationDetailModel> GetInstallationDetail(InstallationIDRequest requestData, CancellationToken ct = default) => Actions.GetInstallationDetail.Post("", requestData, ct);
    public Task<AppInstallCommandDetailModel> GetRequestedInstallationDetail(AppCommandIDRequest requestData, CancellationToken ct = default) => Actions.GetRequestedInstallationDetail.Post("", requestData, ct);
    public Task<EmptyActionResult> Installed(InstallationIDRequest requestData, CancellationToken ct = default) => Actions.Installed.Post("", requestData, ct);
    public Task<EmptyActionResult> RequestDelete(InstallationIDRequest requestData, CancellationToken ct = default) => Actions.RequestDelete.Post("", requestData, ct);
    public Task<EmptyActionResult> RequestedInstallationEnded(AppCommandIDRequest requestData, CancellationToken ct = default) => Actions.RequestedInstallationEnded.Post("", requestData, ct);
    public Task<EmptyRequest> RequestedInstallationStepEnded(AppCommandStepEndedRequest requestData, CancellationToken ct = default) => Actions.RequestedInstallationStepEnded.Post("", requestData, ct);
    public Task<AppInstallCommandDetailModel> RequestInstallation(AddAppInstallCommandRequest requestData, CancellationToken ct = default) => Actions.RequestInstallation.Post("", requestData, ct);
    public sealed record InstallationsGroupActions(AppClientPostAction<InstallationIDRequest, EmptyActionResult> BeginDelete, AppClientPostAction<BeginInstallationRequest, InstallationModel> BeginInstallation, AppClientPostAction<AppCommandIDRequest, AppCommandModel> BeginRequestedInstallation, AppClientPostAction<BeginAppCommandStepRequest, AppCommandStepModel> BeginRequestedInstallationStep, AppClientPostAction<InstallationIDRequest, EmptyActionResult> Deleted, AppClientPostAction<GetInstallationActivitiesRequest, InstallationActivitiesResult> GetInstallationActivities, AppClientPostAction<InstallationIDRequest, InstallationDetailModel> GetInstallationDetail, AppClientPostAction<AppCommandIDRequest, AppInstallCommandDetailModel> GetRequestedInstallationDetail, AppClientGetAction<InstallationQueryRequest> Index, AppClientGetAction<InstallationViewRequest> Installation, AppClientPostAction<InstallationIDRequest, EmptyActionResult> Installed, AppClientPostAction<InstallationIDRequest, EmptyActionResult> RequestDelete, AppClientPostAction<AppCommandIDRequest, EmptyActionResult> RequestedInstallationEnded, AppClientPostAction<AppCommandStepEndedRequest, EmptyRequest> RequestedInstallationStepEnded, AppClientPostAction<AddAppInstallCommandRequest, AppInstallCommandDetailModel> RequestInstallation);
}