// Generated Code
namespace XTI_HubAppClient;
public sealed partial class InstallGroup : AppClientGroup
{
    public InstallGroup(IHttpClientFactory httpClientFactory, XtiTokenAccessor xtiTokenAccessor, AppClientUrl clientUrl, AppClientOptions options) : base(httpClientFactory, xtiTokenAccessor, clientUrl, options, "Install")
    {
        Actions = new InstallGroupActions(AddAdminUser: CreatePostAction<AddAdminUserRequest, AppUserModel>("AddAdminUser"), AddInstallationUser: CreatePostAction<AddInstallationUserRequest, AppUserModel>("AddInstallationUser"), AddOrUpdateApps: CreatePostAction<AddOrUpdateAppsRequest, AppModel[]>("AddOrUpdateApps"), AddOrUpdateVersions: CreatePostAction<AddOrUpdateVersionsRequest, EmptyActionResult>("AddOrUpdateVersions"), AddSystemUser: CreatePostAction<AddSystemUserRequest, AppUserModel>("AddSystemUser"), BeginInstallation: CreatePostAction<GetInstallationRequest, EmptyActionResult>("BeginInstallation"), ConfigureInstall: CreatePostAction<ConfigureInstallRequest, InstallConfigurationModel>("ConfigureInstall"), ConfigureInstallTemplate: CreatePostAction<ConfigureInstallTemplateRequest, InstallConfigurationTemplateModel>("ConfigureInstallTemplate"), DeleteInstallConfiguration: CreatePostAction<DeleteInstallConfigurationRequest, EmptyActionResult>("DeleteInstallConfiguration"), GetInstallConfigurations: CreatePostAction<GetInstallConfigurationsRequest, InstallConfigurationModel[]>("GetInstallConfigurations"), GetVersion: CreatePostAction<GetVersionRequest, XtiVersionModel>("GetVersion"), GetVersions: CreatePostAction<GetVersionsRequest, XtiVersionModel[]>("GetVersions"), Installed: CreatePostAction<GetInstallationRequest, EmptyActionResult>("Installed"), NewInstallation: CreatePostAction<NewInstallationRequest, NewInstallationResult>("NewInstallation"), RegisterApp: CreatePostAction<RegisterAppRequest, AppModel>("RegisterApp"), SetUserAccess: CreatePostAction<SetUserAccessRequest, EmptyActionResult>("SetUserAccess"));
        Configure();
    }

    partial void Configure();
    public InstallGroupActions Actions { get; }

    public Task<AppUserModel> AddAdminUser(AddAdminUserRequest requestData, CancellationToken ct = default) => Actions.AddAdminUser.Post("", requestData, ct);
    public Task<AppUserModel> AddInstallationUser(AddInstallationUserRequest requestData, CancellationToken ct = default) => Actions.AddInstallationUser.Post("", requestData, ct);
    public Task<AppModel[]> AddOrUpdateApps(AddOrUpdateAppsRequest requestData, CancellationToken ct = default) => Actions.AddOrUpdateApps.Post("", requestData, ct);
    public Task<EmptyActionResult> AddOrUpdateVersions(AddOrUpdateVersionsRequest requestData, CancellationToken ct = default) => Actions.AddOrUpdateVersions.Post("", requestData, ct);
    public Task<AppUserModel> AddSystemUser(AddSystemUserRequest requestData, CancellationToken ct = default) => Actions.AddSystemUser.Post("", requestData, ct);
    public Task<EmptyActionResult> BeginInstallation(GetInstallationRequest requestData, CancellationToken ct = default) => Actions.BeginInstallation.Post("", requestData, ct);
    public Task<InstallConfigurationModel> ConfigureInstall(ConfigureInstallRequest requestData, CancellationToken ct = default) => Actions.ConfigureInstall.Post("", requestData, ct);
    public Task<InstallConfigurationTemplateModel> ConfigureInstallTemplate(ConfigureInstallTemplateRequest requestData, CancellationToken ct = default) => Actions.ConfigureInstallTemplate.Post("", requestData, ct);
    public Task<EmptyActionResult> DeleteInstallConfiguration(DeleteInstallConfigurationRequest requestData, CancellationToken ct = default) => Actions.DeleteInstallConfiguration.Post("", requestData, ct);
    public Task<InstallConfigurationModel[]> GetInstallConfigurations(GetInstallConfigurationsRequest requestData, CancellationToken ct = default) => Actions.GetInstallConfigurations.Post("", requestData, ct);
    public Task<XtiVersionModel> GetVersion(GetVersionRequest requestData, CancellationToken ct = default) => Actions.GetVersion.Post("", requestData, ct);
    public Task<XtiVersionModel[]> GetVersions(GetVersionsRequest requestData, CancellationToken ct = default) => Actions.GetVersions.Post("", requestData, ct);
    public Task<EmptyActionResult> Installed(GetInstallationRequest requestData, CancellationToken ct = default) => Actions.Installed.Post("", requestData, ct);
    public Task<NewInstallationResult> NewInstallation(NewInstallationRequest requestData, CancellationToken ct = default) => Actions.NewInstallation.Post("", requestData, ct);
    public Task<AppModel> RegisterApp(RegisterAppRequest requestData, CancellationToken ct = default) => Actions.RegisterApp.Post("", requestData, ct);
    public Task<EmptyActionResult> SetUserAccess(SetUserAccessRequest requestData, CancellationToken ct = default) => Actions.SetUserAccess.Post("", requestData, ct);
    public sealed record InstallGroupActions(AppClientPostAction<AddAdminUserRequest, AppUserModel> AddAdminUser, AppClientPostAction<AddInstallationUserRequest, AppUserModel> AddInstallationUser, AppClientPostAction<AddOrUpdateAppsRequest, AppModel[]> AddOrUpdateApps, AppClientPostAction<AddOrUpdateVersionsRequest, EmptyActionResult> AddOrUpdateVersions, AppClientPostAction<AddSystemUserRequest, AppUserModel> AddSystemUser, AppClientPostAction<GetInstallationRequest, EmptyActionResult> BeginInstallation, AppClientPostAction<ConfigureInstallRequest, InstallConfigurationModel> ConfigureInstall, AppClientPostAction<ConfigureInstallTemplateRequest, InstallConfigurationTemplateModel> ConfigureInstallTemplate, AppClientPostAction<DeleteInstallConfigurationRequest, EmptyActionResult> DeleteInstallConfiguration, AppClientPostAction<GetInstallConfigurationsRequest, InstallConfigurationModel[]> GetInstallConfigurations, AppClientPostAction<GetVersionRequest, XtiVersionModel> GetVersion, AppClientPostAction<GetVersionsRequest, XtiVersionModel[]> GetVersions, AppClientPostAction<GetInstallationRequest, EmptyActionResult> Installed, AppClientPostAction<NewInstallationRequest, NewInstallationResult> NewInstallation, AppClientPostAction<RegisterAppRequest, AppModel> RegisterApp, AppClientPostAction<SetUserAccessRequest, EmptyActionResult> SetUserAccess);
}