// Generated Code
namespace XTI_HubAppClient;
public sealed partial class InstallationsGroup : AppClientGroup
{
    public InstallationsGroup(IHttpClientFactory httpClientFactory, XtiTokenAccessor xtiTokenAccessor, AppClientUrl clientUrl, AppClientOptions options) : base(httpClientFactory, xtiTokenAccessor, clientUrl, options, "Installations")
    {
        Actions = new InstallationsGroupActions(AddDeleteCommand: CreatePostAction<InstallationIDRequest, AppDeleteCommandDetailModel>("AddDeleteCommand"), AddInstallCommand: CreatePostAction<AddInstallCommandRequest, AppInstallCommandDetailModel>("AddInstallCommand"), BeginCommand: CreatePostAction<AppCommandIDRequest, AppCommandModel>("BeginCommand"), BeginCommandStep: CreatePostAction<BeginAppCommandStepRequest, AppCommandStepModel>("BeginCommandStep"), BeginDelete: CreatePostAction<InstallationIDRequest, EmptyActionResult>("BeginDelete"), BeginInstallation: CreatePostAction<BeginInstallationRequest, InstallationModel>("BeginInstallation"), CommandEnded: CreatePostAction<AppCommandIDRequest, EmptyActionResult>("CommandEnded"), CommandStepEnded: CreatePostAction<AppCommandStepEndedRequest, EmptyRequest>("CommandStepEnded"), Deleted: CreatePostAction<InstallationIDRequest, EmptyActionResult>("Deleted"), GetDeleteCommandDetail: CreatePostAction<AppCommandIDRequest, AppDeleteCommandDetailModel>("GetDeleteCommandDetail"), GetInstallationCommandDetail: CreatePostAction<AppCommandIDRequest, AppInstallCommandDetailModel>("GetInstallationCommandDetail"), GetInstallationDetail: CreatePostAction<InstallationIDRequest, InstallationDetailModel>("GetInstallationDetail"), GetPendingCommands: CreatePostAction<GetPendingCommandsRequest, AppCommandModel[]>("GetPendingCommands"), Index: CreateGetAction<InstallationQueryRequest>("Index"), Installation: CreateGetAction<InstallationViewRequest>("Installation"), Installed: CreatePostAction<InstallationIDRequest, EmptyActionResult>("Installed"));
        Configure();
    }

    partial void Configure();
    public InstallationsGroupActions Actions { get; }

    public Task<AppDeleteCommandDetailModel> AddDeleteCommand(InstallationIDRequest requestData, CancellationToken ct = default) => Actions.AddDeleteCommand.Post("", requestData, ct);
    public Task<AppInstallCommandDetailModel> AddInstallCommand(AddInstallCommandRequest requestData, CancellationToken ct = default) => Actions.AddInstallCommand.Post("", requestData, ct);
    public Task<AppCommandModel> BeginCommand(AppCommandIDRequest requestData, CancellationToken ct = default) => Actions.BeginCommand.Post("", requestData, ct);
    public Task<AppCommandStepModel> BeginCommandStep(BeginAppCommandStepRequest requestData, CancellationToken ct = default) => Actions.BeginCommandStep.Post("", requestData, ct);
    public Task<EmptyActionResult> BeginDelete(InstallationIDRequest requestData, CancellationToken ct = default) => Actions.BeginDelete.Post("", requestData, ct);
    public Task<InstallationModel> BeginInstallation(BeginInstallationRequest requestData, CancellationToken ct = default) => Actions.BeginInstallation.Post("", requestData, ct);
    public Task<EmptyActionResult> CommandEnded(AppCommandIDRequest requestData, CancellationToken ct = default) => Actions.CommandEnded.Post("", requestData, ct);
    public Task<EmptyRequest> CommandStepEnded(AppCommandStepEndedRequest requestData, CancellationToken ct = default) => Actions.CommandStepEnded.Post("", requestData, ct);
    public Task<EmptyActionResult> Deleted(InstallationIDRequest requestData, CancellationToken ct = default) => Actions.Deleted.Post("", requestData, ct);
    public Task<AppDeleteCommandDetailModel> GetDeleteCommandDetail(AppCommandIDRequest requestData, CancellationToken ct = default) => Actions.GetDeleteCommandDetail.Post("", requestData, ct);
    public Task<AppInstallCommandDetailModel> GetInstallationCommandDetail(AppCommandIDRequest requestData, CancellationToken ct = default) => Actions.GetInstallationCommandDetail.Post("", requestData, ct);
    public Task<InstallationDetailModel> GetInstallationDetail(InstallationIDRequest requestData, CancellationToken ct = default) => Actions.GetInstallationDetail.Post("", requestData, ct);
    public Task<AppCommandModel[]> GetPendingCommands(GetPendingCommandsRequest requestData, CancellationToken ct = default) => Actions.GetPendingCommands.Post("", requestData, ct);
    public Task<EmptyActionResult> Installed(InstallationIDRequest requestData, CancellationToken ct = default) => Actions.Installed.Post("", requestData, ct);
    public sealed record InstallationsGroupActions(AppClientPostAction<InstallationIDRequest, AppDeleteCommandDetailModel> AddDeleteCommand, AppClientPostAction<AddInstallCommandRequest, AppInstallCommandDetailModel> AddInstallCommand, AppClientPostAction<AppCommandIDRequest, AppCommandModel> BeginCommand, AppClientPostAction<BeginAppCommandStepRequest, AppCommandStepModel> BeginCommandStep, AppClientPostAction<InstallationIDRequest, EmptyActionResult> BeginDelete, AppClientPostAction<BeginInstallationRequest, InstallationModel> BeginInstallation, AppClientPostAction<AppCommandIDRequest, EmptyActionResult> CommandEnded, AppClientPostAction<AppCommandStepEndedRequest, EmptyRequest> CommandStepEnded, AppClientPostAction<InstallationIDRequest, EmptyActionResult> Deleted, AppClientPostAction<AppCommandIDRequest, AppDeleteCommandDetailModel> GetDeleteCommandDetail, AppClientPostAction<AppCommandIDRequest, AppInstallCommandDetailModel> GetInstallationCommandDetail, AppClientPostAction<InstallationIDRequest, InstallationDetailModel> GetInstallationDetail, AppClientPostAction<GetPendingCommandsRequest, AppCommandModel[]> GetPendingCommands, AppClientGetAction<InstallationQueryRequest> Index, AppClientGetAction<InstallationViewRequest> Installation, AppClientPostAction<InstallationIDRequest, EmptyActionResult> Installed);
}