global using Microsoft.Extensions.DependencyInjection;
global using XTI_App.Abstractions;
global using XTI_App.Api;
global using XTI_Hub;
global using XTI_Hub.Abstractions;
global using XTI_WebApp.Abstractions;
global using XTI_WebApp.Api;
global using XTI_HubDB.Entities;
global using XTI_TempLog.Abstractions;
